MEMORY {
        ram    : ORIGIN = 0x20000000, LENGTH = 0xf000
        rom    : ORIGIN = 0x00000000, LENGTH = 0xf000
}

SECTIONS {
	.text : {
		_stext = . ;
		*(.text)
		*(.rodata)
		. = ALIGN(4);
		_etext = . ;
	} > rom
	.data : {
		_sdata = . ;
		*(.data)
		*(.glue_7*)
		. = ALIGN(4);
		_edata = . ;
	} > ram
	.bss : {
		_sbss = . ;
		*(.bss)
		. = ALIGN(4);
		_ebss = . ;
	} > ram
}
